### ISSUE TITLE
Cant detect what potion player has, only material name

### ISSUE THREAD

**Issue by broken1arrow** [PlaceholderAPI/CheckItem-Expansion#20]
If it was reable way to detect you could buy it from players and even change lore if you have item or not.
Like this example, if you don´t have the item you don´t get sell part in the lore. 

The name on a example potion ingame.

name: potion Material: POTION
Potion (string): Minecraft:long_fire_resistance

Spigot name long_fire_resistance

And the check item I use only work if you add a lore to the item and is not a good way to fix the problem, has try all metods and even java scrips placeholders.

<details>
 <summary>example menu</summary>

```
  '1_no_potion':
    material: potion
    slot: 10
    priority: 8
    view_requirement:
      requirements:
        potion:
           type: string equals
           input: '%checkitem_lorecontains:Häxbrygd Night Vision (3:00)%'
           output: 'no'
           material: 'POTION'
        money_requirement:
          type: '>='
          input: '%vault_eco_balance_fixed%'
          output: 300
    display_name: '&2Buy Night Vision'
    lore:
    - ''
    - '&6&l<&#ff0537&lYou dont have'
    - '&#ff0537&lpotion of Night Vision&6&l>'
    - ''
    - '------------------'
    - '&aYou have:  %vault_eco_balance_fixed% &eⒼ'
    - '&b• buy: 300 gold'
  #  - '&b• Sell: 30 gold'
    - '------------------'
    - '&8 (left click for buy)'
   # - '&8 (right click for sell)'
```

</details>
