### ISSUE TITLE
Need CheckItem Only For Inventory

### ISSUE THREAD

**Issue by TailedPoog420** [PlaceholderAPI/CheckItem-Expansion#29]
Hey there,

I'm trying to create a DeluxeMenus shop using the following:

```
  'cobblestone':
    material: COBBLESTONE
    amount: 64
    slot: 0
    display_name: '&3Cobblestone'
    lore:
    - ''
    - '&7Buy price: &a$500&7. (Left-click)'
    - '&7Sell price: &c$75&7. (Right-click)'
    left_click_commands:
    - '[console] eco take %player_name% 500'
    - '[console] give %player_name% COBBLESTONE 64'
    - '[message] &7You bought 64 x cobblestone for $500.'
    left_click_requirement:
      requirements:
        anything_here:
          type: has money
          amount: 500
      deny_commands:
      - '[message] &7You do not have enough money.'
    right_click_commands:
    - '[console] eco give %player_name% 75'
    - '[console] clear %player_name% COBBLESTONE 64'
    - '[message] &7You sold 64 x cobblestone for $75.'
    right_click_requirement:
      requirements:
        anything_here:
          type: '>='
          input: '%checkitem_amount_mat:COBBLESTONE,strict%'
          output: '64'
      deny_commands:
      - '[message] &7You do not have enough of this item to sell.'
```

Since the ` clear %player_name% COBBLESTONE 64 ` only seems to work for inventory slots and for not off-hand slots or armor slots, we need a way of using ` %checkitem_amount_mat:COBBLESTONE,strict% ` but only for the inventory, so that infinite economy exploits aren't possible by simply putting the 64 COBBLESTONE in the off-hand slot and bypassing the right_click_requirement because the clear doesn't remove it from that slot.
