### ISSUE TITLE
Issue when items are spread into many small stacks

### ISSUE THREAD

**Issue by henkekalmar** [PlaceholderAPI/CheckItem-Expansion#8]
Here's a gif demonstrating it: https://gyazo.com/7c0c6e1dbad191aa103b2ab60624fa41

Here's what the config is: 
```
    left_click_requirement:
      requirements:
        sell:
          type: string equals
          input: '%checkitem_amt:8,mat:IRON_INGOT%'
          output: 'yes'
```

It works fine for as long as you have a stack in your inventory that is greater than 8 but when that is finally removed it stops working.
